# Generated by Django 3.2.7 on 2021-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_studies',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=15)),
                ('industry', models.CharField(blank=True, max_length=20)),
                ('img', models.ImageField(upload_to='Images')),
                ('brand', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
    ]
