# Generated by Django 3.2.7 on 2021-10-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_story',
            fields=[
                ('case_studies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caseStudies.case_studies')),
                ('heading', models.CharField(max_length=20)),
            ],
            bases=('caseStudies.case_studies',),
        ),
    ]
