# Generated by Django 3.2.7 on 2021-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0002_case_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='case_story',
        ),
    ]
